apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
  type: NodePort
  ports:
    # port: referred when OTHER container try to connect to this pod
    - port: 3050
      targetPort: 3000
      nodePort: 31515
  selector:
    # refer to labels/component on client-pod
    component: web