apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  # connected by the selector
  labels:
    component: web
spec:
  containers:
    # - : ハッシュ
    # https://zenn.dev/mkosakana/articles/459d6126236bf0#%E9%85%8D%E5%88%97%E5%86%85%E3%81%AE%E3%83%8F%E3%83%83%E3%82%B7%E3%83%A5
    - name: client
      image: stephengrider/multi-worker
      ports:
        - containerPort: 9999
